name: anatprep
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - nibabel
  - nilearn
  - numpy
  - scipy
  - click
  - pyyaml
  - matplotlib
  - pip
  - pip:
      - install git+https://github.com/Gilles86/pymp2rage
